version: '3.8'

services:
  eureka-server:
    image: eureka-server
    container_name: eureka
    hostname: eureka-server
    ports:
      - "8761:8761"
    networks:
      - eureka-network

networks:
  eureka-network:
    driver: bridge